### ISSUE TITLE
Patching an item leads to error deserializing values

### ISSUE THREAD

**Issue by CrazyCrud** [elabftw/elabapi-python#17] opened 2024-03-13 09:31 UTC
### Detailed description of the problem
When I want to patch a new item via the API, the following error is caused:
```
items_api.patch_item(item_id, body={'title': row['NAME'], 'metadata': get_metadata_from_row(row)})
except ApiException as e:
print("Exception when calling ItemsApi->postItem: %s\n" % e)

File "/usr/local/lib/python3.10/site-packages/elabapi_python/api/items_api.py", line 246, in patch_item

(data) = self.patch_item_with_http_info(id, **kwargs)  # noqa: E501

File "/usr/local/lib/python3.10/site-packages/elabapi_python/api/items_api.py", line 312, in patch_item_with_http_info

return self.api_client.call_api(

File "/usr/local/lib/python3.10/site-packages/elabapi_python/api_client.py", line 316, in call_api

return self.__call_api(resource_path, method,

File "/usr/local/lib/python3.10/site-packages/elabapi_python/api_client.py", line 160, in __call_api

return_data = self.deserialize(response_data, response_type)

File "/usr/local/lib/python3.10/site-packages/elabapi_python/api_client.py", line 232, in deserialize

return self.__deserialize(data, response_type)

File "/usr/local/lib/python3.10/site-packages/elabapi_python/api_client.py", line 271, in __deserialize

return self.__deserialize_model(data, klass)

File "/usr/local/lib/python3.10/site-packages/elabapi_python/api_client.py", line 618, in __deserialize_model

if (data is not None and

File "/usr/local/lib/python3.10/site-packages/elabapi_python/api_client.py", line 263, in __deserialize

return self.__deserialize_primitive(data, klass)

File "/usr/local/lib/python3.10/site-packages/elabapi_python/api_client.py", line 545, in __deserialize_primitive

return klass(data)

ValueError: invalid literal for int() with base 10: 'Default'
```   

I have orientated myself on this example: [08-create-items-add-metadata.py](https://github.com/elabftw/elabapi-python/blob/master/examples/08-create-items-add-metadata.py)   

### Do you have any idea what may have caused this?
The resource category's title (in my case titled `'Default'`) is interpreted as an `int`, so the casting does not work correctly. 

### Additional information
- elab 4.8.6
- elabapi-python 5.0.2
       
Thank you in advance!

Best regards
Constantin

**Comment by NicolasCARPi** [comment] 2024-03-13 10:13
Hello,

This issue cannot be reproduced, so my only recommendation would be to upgrade eLabFTW to version 5.0.3. You can try on the demo and see if you can reproduce the issue.

Closing this because only latest stable version is supported, and you're two major versions behind.

**Closed by NicolasCARPi** 2024-03-13 10:13 UTC
